### ISSUE TITLE
Request API 服务不可用

### ISSUE THREAD

**Issue by ABUAIJUTIE** [hasscc/catlink#3]
一直返回

> Request: /token/device/union/list/sorted
> {'returnCode': 1000, 'toast': False, 'msg': '设备不在线或其他异常', 'data': {}, 'timestamp': 1656923378237, 'success': False}
> 

请求是
```
service: catlink.request_api
data:
  api: /token/device/union/list/sorted
  params:
    key: val
  method: GET
  throw: true
target:
  entity_id: sensor.cat_scooper_last_log

```
