### ISSUE TITLE
New install of hasscc/catlink - cannot authenticate account(s) [password incorrect]

### ISSUE THREAD

**Issue by hassystuf** [hasscc/catlink#35]
Installed via HACS.
Running on Home Assistant Green, recently migrated from a VM.
HASS versions:
Core: 2024.12.1
Supervisor: 2024.11.4
Operating System: 14.0
Frontend: 20241127.6

HACS versions:
Integration version: 2.0.1
Frontend version: 20240903140523

configuration.yaml:
```
catlink:
  # Single account
  phone: 22*******7 # Username of Catlink APP (without country code)
  password: ********** # Password
  phone_iac: 1 # Optional, International access code, default is 86 (China)
  api_base: https://app-usa.catlinks.cn/api/ # Optional, default is China server: https://app.catlinks.cn/api/ (see API Regions)
  scan_interval: 00:01:00 # Optional, default is 00:01:00
  language: "en_GB"

  devices:
    - name: "Scooper Pro"
      mac: ************
    - name: "Scooper SE"
      mac: ************
```

Error message:

```
This error originated from a custom integration.

Logger: custom_components.catlink.const
Source: custom_components/catlink/modules/account.py:133
integration: CatLink (documentation, issues)
First occurred: 11:49:01 AM (2 occurrences)
Last logged: 11:49:01 AM

Login 22*******7 failed: [{'returnCode': 2002, 'toast': False, 'msg': 'Password Incorrect', 'data': {}, 'timestamp': '1733676541571', 'success': False}, {'platform': 'ANDROID', 'internationalCode': 1, 'mobile': '22*******7', 'password': '************', 'noncestr': ************, 'sign': '************'}]
Login 22*******7 failed: [{'returnCode': 2002, 'toast': False, 'msg': 'Password Incorrect', 'data': {}, 'timestamp': '1733676541642', 'success': False}, {'platform': 'ANDROID', 'internationalCode': 1, 'mobile': '22*******7', 'password': '************', 'noncestr': ************, 'sign': '************'}]

```

I have attempted logging in with two accounts. Each has a different US phone number associated. I've changed passwords, wrapped them in quotes or not in the config noted above, and attempted the different API endpoints, languages, and scan intervals. All result in errors, but this is the most 'useful' because at least it's giving me _something_. 

I've attempted not adding devices, or just adding one, to no avail.

What am I missing here? I figured the quotes _might_ be the issue here as there are config elements in the readme that show doing both with and without them, but that doesn't seem to have a bearing on whether the plugin will work.
